- MANIFEST.in
- conf/config.py
- message_tagging_service/__init__.py
- message_tagging_service/config.py
- message_tagging_service/messaging.py
- message_tagging_service/tagging_service.py
- message_tagging_service/utils.py
- tests/data/config.py
- tests/test_config.py
- tests/test_messaging.py
- tests/test_service.py
This change makes it possible to install config file into /etc/mts/, and
load config for development and production.
If MTS_DEV is defined in environment variables, loading config from
conf/config.py, otherwise loading from /etc/mts/config.py.
There is another choice to overwrite both of them, that is to define
MTS_CONFIG_FILE which should point to an existing Python file including
configuration class.
> Decouple config file from message_tagging_service module

- message_tagging_service/tagging_service.py
This is a little change to the code that reflects only one rule is matched.
> Refine code for the first match wins

- message_tagging_service/tagging_service.py
- tests/test_service.py
MBS always generates a corresponding -devel module build in Koji. This
should also be tagged with the same tag as the "main" module build.
> Tag -devel CG Koji build

- message_tagging_service/consumer.py
- tests/test_consumer.py
When a module build in init state, koji_tag is just None. Original log
message logs "Skip module build None ...", which does not make sense and
hard to know which module build is skipped if DEBUG log level is
disabled. Instead, this patch construct module NSVC explicitly inside
log message.
> Better log when module build in init state

- README.rst
This fixes the rendered layout to put the badges into one line intead of
being rendered into multiple lines.
> Fix badges in README

- README.rst
- message_tagging_service/tagging_service.py
- tests/test_service.py
Original event topic mts.build.tagged is replaced with two new specific
topics, mts.build.tag.requested and mts.build.tag.unmatched.
> Refine event topics

- Dockerfile
- docker/entrypoint.sh
- message_tagging_service/messaging.py
- message_tagging_service/monitor.py
- message_tagging_service/tagging_service.py
- message_tagging_service/web.py
- requirements.txt
This metrics endpoint is for expose data for Prometheus.
The docker image executes fedmsg-hub in background and expose 8080 for HTTP
requests.
> Expose metrics endpoint for monitoring

- Dockerfile
> Add missing \ to break dnf-install command properly in Dockerfile

- docker/entrypoint.sh
This is for debugging MTS in Openshift, which reports error "worker timeout".
> Set gunicorn log level to debug

- docker/entrypoint.sh
* Restore to use just 1 worker as MTS web endpoint is simple enough to response
GET request and return data from memory.
* Make log level configurable by environment variable.
> Adjust gunicorn command line options

- message_tagging_service/tagging_service.py
- tests/data/mts-test-rules.yaml
- tests/test_service.py
The worst case is when a module build with state build comes in, there is no
rule defined for this state, which probably only has rules for state done and
ready. In this case, MTS will try to test the module build with every rule.
With this patch, the build state is checked before starting to match rules. And
rules with same build state are checked only, others with different build state
are skipped.
> Reduce the number of tries to match rules

- message_tagging_service/messaging.py
- message_tagging_service/monitor.py
This is to be able to catch `messaging_tx_failed` in monitoring/alerting/graphing for MTS, as it already works "by magic" for the rest of our services.
Without this, we'd have to do some relabeling or create a special alert for it etc.
> Change the metric name to be in sync with other services

- docker/install-dependencies.sh
- tests/test_service.py
fedora-packager provides config files for Koji and Kerberos
authentication, which could make it a little bit easier to deploy MTS in
Fedora.
> Install packages for Fedora container

- message_tagging_service/consumer.py
- tests/test_consumer.py
- tox.ini
* The original RHMessage works incorrectly with the original message
received from UMB.
* _consumer_wrapper missed an argument inside rhmsg_backend
function.
* More tests are added for consumer module.
* Show test coverage.
> Fix consumer and add tests

- Dockerfile
Set this image version explicitly otherwise the built image will still
have the base image version, e.g. 29.
> Set image version to latest

- message_tagging_service/tagging_service.py
This will help diagnose errors in the future.
> Log the exception when tag failures occur

- docker/entrypoint.sh
The message_tagging_service runs as a python module. In the container
image, gunicorn is also run for prometheus metrics. This is a secondary
capability of the container image. The most important being the python
process that run MTS. By making it run in the foreground,
OpenShift/Kubernetes can properly determine if the pod needs to be
restarted in case MTS quits unexpectedly.
> Run mts in the foreground

- Dockerfile
- docker/install-dependencies.sh
Also explicitly install python3-pip, as it's not part of the Fedora
image anymore.
Signed-off-by: Hunor Csomortáni <csomh@redhat.com>
> Upgrade base image to Fedora 31

- message_tagging_service/consumer.py
- message_tagging_service/tagging_service.py
- tests/test_consumer.py
- tests/test_service.py
In this PR, MTS ignores `scratch: xxx` if it appears in a rule definition, and ignore the message of a scratch module build.
> Do not handle scratch build

- Dockerfile
rcm-tools-repo does not have fedora 31 support for now.
> Fallback to fedora:30 base image

- .travis.yml
Image registry.fedoraproject.org/fedora:29 is not available, that breaks
CI at the step of "docker pull".
> Use image fedora:31 in CI

- tests/test_service.py
> unittest: the latest koji use gssapi_login instead of krb_login

- conf/config.py
- message_tagging_service/config.py
- message_tagging_service/consumer.py
- tests/test_consumer.py
This is to have a "whitelist" of `build_state` which only allows "ready", "done" builds' msg to proceed with rules by default config
> consumer: only receive msgs with build_state is ready or done by default
