fedora-modularity/message-tagging-service

- .travis-ci.yml
> Add Travis-ci

- README.md
- fedmsg.d/config.py
- fedmsg.d/mts.py
- message_tagging_service/consumer.py
- message_tagging_service/mts_config.py
- message_tagging_service/tagging_service.py
- requirements.txt
- setup.py
- tests/test_consumer.py
- tests/test_service.py
> Run tagging service in fedmsg consumer approach

- README.md
- fedmsg.d/config.py
- fedmsg.d/mts.py
- message_tagging_service/consumer.py
- message_tagging_service/messaging.py
- message_tagging_service/mts_config.py
- message_tagging_service/tagging_service.py
- requirements.txt
- setup.py
- tests/test_consumer.py
- tests/test_messaging.py
- tests/test_service.py
This requires #6. After that is merged, I'll rebase this PR.
> Add messaging

- message_tagging_service/consumer.py
- tests/test_consumer.py
> Fix consumer to get event message dict

- message_tagging_service/mts_config.py
Config rule_config has a wrong value that was modified for local debug.
It should not be committed into code base. This fixes that.
> Fix config

- .travis-ci.yml
- .travis.yml
- README.md
> Run Travis-CI job

- conf/config.py
- fedmsg.d/config.py
- fedmsg.d/logging.py
- message_tagging_service/__init__.py
- message_tagging_service/messaging.py
- message_tagging_service/tagging_service.py
- message_tagging_service/utils.py
- tests/test_service.py
- tests/test_utils.py
Most of the changes were done after testing MTS locally.
> Minor fixes

- MANIFEST.in
> Add missing files to tarball generated by sdist

- conf/config.py
- message_tagging_service/__init__.py
- message_tagging_service/config.py
- tests/data/config.py
- tests/test_config.py
Signed-off-by: Valerij Maljulin <vmaljuli@redhat.com>
> Base class for configuration profiles

- message_tagging_service/tagging_service.py
- tests/test_service.py
A rule can be defined to use a value from modulemd in the destination
tag. In the case where the value from modulemd is a list of value,
multiple destination tags should be applied.
> Handle multiple tags for single rule

- Dockerfile
Latest version has the following issue:
https://github.com/mokshaproject/moksha/issues/69
> Use known good version of moksha-hub

- README.rst
- setup.py
Lots of changes have been merged since version 0.2 and the code from master branch is working on stage already. Let's make a new release. :tada:
> Release 0.3

- message_tagging_service/tagging_service.py
- tests/test_service.py
As a result, from this message, it is easy to know what tags should be
applied to a module build, and which tags are requested successfully to
be applied, and which ones fail.
Fixes FACTORY-3928
> Include failed tagBuild task request in build.tag.requested message

- README.rst
> Add container badge in README

- Dockerfile
> Add missing deps to Dockerfile

- docker/entrypoint.sh
Let's try again to debug the issue in Upshift. Hopefully, we are lucky with
this change.
> Increase the number of workers to run the web app

- README.rst
- setup.py
> Release 0.4

- conf/config.py
- message_tagging_service/consumer.py
- message_tagging_service/tagging_service.py
- tests/test_consumer.py
- tests/test_service.py
> Match module build by build state

- README.rst
- setup.py
> Release 0.5

- Dockerfile
> Set USER for fedmsg to publish message

- message_tagging_service/tagging_service.py
> Remove duplicate code handling rule scratch and development

- message_tagging_service/consumer.py
> Fix variable name inside log message format

- README.rst
> Massive updates to README.rst

- message_tagging_service/consumer.py
- message_tagging_service/messaging.py
- message_tagging_service/tagging_service.py
This change aims to log enough logs for easy debug even if the logging
level is set to INFO.
> Better logs

- message_tagging_service/tagging_service.py
> Fix param type of dest_tags

- conf/config.py
- message_tagging_service/consumer.py
> Allow durable queues when using rhmsg

- message_tagging_service/tagging_service.py
- tests/data/mts-test-rules.yaml
- tests/test_service.py
> Add support for complex destinations

- README.rst
- setup.py
> Release 0.7

- .travis.yml
> CI: Fix missing command to run tests

- message_tagging_service/consumer.py
- tests/test_consumer.py
it is a typo there should be fixed
> fix the field from build_state to state_name

- message_tagging_service/monitor.py
Shout out to @raks-tt who found this problem and propose this change
> prometheus: do not init duplicate ProcessCollector

- message_tagging_service/monitor.py
This reverts commit 66e658588ee7d0049613bcbe5b9141b5822a2744.
> Revert "prometheus: do not init duplicate ProcessCollector"
